In [1]:
import torch
import numpy as np

In [2]:
# Create Tensor
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

# Create Tensor from numpy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# Create Tensor from another tensor
x_ones = torch.ones_like(x_data) # ones, retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # std normal randn, overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3120, 0.2559],
        [0.3683, 0.9316]]) 



In [3]:
# Define Tensor Shape
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9236, 0.4680, 0.8060],
        [0.7392, 0.1524, 0.0272]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# Tensor Attributes
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [5]:
# Use GPU
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [9]:
# Change Value
tensor = torch.rand(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[0.0416, 0.0000, 0.5894, 0.2760],
        [0.7540, 0.0000, 0.9362, 0.7757],
        [0.1288, 0.0000, 0.9007, 0.9946],
        [0.2331, 0.0000, 0.8375, 0.5056]])


In [11]:
# Join Tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t1, '\n', t2)

tensor([[0.0416, 0.0000, 0.5894, 0.2760, 0.0416, 0.0000, 0.5894, 0.2760, 0.0416,
         0.0000, 0.5894, 0.2760],
        [0.7540, 0.0000, 0.9362, 0.7757, 0.7540, 0.0000, 0.9362, 0.7757, 0.7540,
         0.0000, 0.9362, 0.7757],
        [0.1288, 0.0000, 0.9007, 0.9946, 0.1288, 0.0000, 0.9007, 0.9946, 0.1288,
         0.0000, 0.9007, 0.9946],
        [0.2331, 0.0000, 0.8375, 0.5056, 0.2331, 0.0000, 0.8375, 0.5056, 0.2331,
         0.0000, 0.8375, 0.5056]]) 
 tensor([[[0.0416, 0.0000, 0.5894, 0.2760],
         [0.0416, 0.0000, 0.5894, 0.2760],
         [0.0416, 0.0000, 0.5894, 0.2760]],

        [[0.7540, 0.0000, 0.9362, 0.7757],
         [0.7540, 0.0000, 0.9362, 0.7757],
         [0.7540, 0.0000, 0.9362, 0.7757]],

        [[0.1288, 0.0000, 0.9007, 0.9946],
         [0.1288, 0.0000, 0.9007, 0.9946],
         [0.1288, 0.0000, 0.9007, 0.9946]],

        [[0.2331, 0.0000, 0.8375, 0.5056],
         [0.2331, 0.0000, 0.8375, 0.5056],
         [0.2331, 0.0000, 0.8375, 0.5056]]])


In [13]:
# Multiplying Tensors
tensor = torch.tensor(data)
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[ 1,  4],
        [ 9, 16]]) 

tensor * tensor 
 tensor([[ 1,  4],
        [ 9, 16]])


In [17]:
# Matrix Multiplication
print(f"tensor:\n{tensor}\n{tensor}\n")
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor:
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])

tensor.matmul(tensor.T) 
 tensor([[ 5, 11],
        [11, 25]]) 

tensor @ tensor.T 
 tensor([[ 5, 11],
        [11, 25]])


In [18]:
# In-place operations
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1, 2],
        [3, 4]]) 

tensor([[6, 7],
        [8, 9]])
